CREATE TABLE IF NOT EXISTS users (
id SERIAL PRIMARY KEY,
discord_id TEXT UNIQUE NOT NULL,
username TEXT NOT NULL,
subdomain TEXT UNIQUE NOT NULL,
token TEXT
);


CREATE TABLE IF NOT EXISTS files (
id SERIAL PRIMARY KEY,
user_id INTEGER REFERENCES users(id),
name TEXT NOT NULL,
slug TEXT UNIQUE NOT NULL,
path TEXT NOT NULL,
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);